import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { Building2, CheckCircle2, Heart, LayoutDashboard, ListFilter, LogOut, Menu, Phone, Plus, Search, ShieldCheck, Upload, X } from 'lucide-react'
import { motion } from 'framer-motion'
import { business } from './config/business'
import { demoProperties } from './data/demoProperties'
import { isAdmin, isSupabaseConfigured, type Property, supabase } from './lib/supabase'
import { AdminDashboard, AdminGuard, AdminLogin, ListYourProperty, PropertyForm } from './Admin'

const money = (p: Property) => p.price_text || (p.purpose === 'rent' ? `₹${(p.rent || 0).toLocaleString('en-IN')} / month` : `₹${(p.price || 0).toLocaleString('en-IN')}`)
const image = (p: Property) => p.cover_image || p.images?.[0] || '/assets/ak-vista-hero.png'
const localities = ['Gangapur Road', 'College Road', 'Indira Nagar', 'Govind Nagar', 'Pathardi Phata', 'Makhmalabad', 'Panchavati', 'Nashik Road', 'Deolali', 'Trimbak Road']

function Header() {
  const [open, setOpen] = useState(false)
  const nav = [['Buy','/buy'],['Rent','/rent'],['Commercial','/commercial'],['Plots','/plots'],['New Projects','/new-projects'],['About','/about'],['Contact','/contact']]
  return <header className="header"><Link className="logo" to="/"><span>AK</span> VISTA<i/></Link><button className="mobile-menu" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X/> : <Menu/>}</button><nav className={open ? 'open' : ''}>{nav.map(([name,to]) => <Link key={to} onClick={() => setOpen(false)} to={to}>{name}</Link>)}</nav><div className="header-actions"><a href={business.phoneHref} aria-label="Call AK Vista"><Phone size={17}/></a><a className="outline-button" href={business.whatsappHref} target="_blank" rel="noreferrer">WhatsApp</a><Link className="gold-button" to="/list-your-property">List Your Property</Link></div></header>
}

function Footer() { return <footer className="footer"><div><Link className="logo" to="/"><span>AK</span> VISTA<i/></Link><p>Independent Real Estate Consultant.<br/>{business.city}</p></div><div><b>Contact</b><a href={business.phoneHref}>{business.phone}</a><a href={`mailto:${business.email}`}>{business.email}</a><a href={business.instagram} target="_blank" rel="noreferrer">Instagram ↗</a></div><div><b>Explore</b><Link to="/properties">All Properties</Link><Link to="/list-your-property">List Your Property</Link><Link to="/privacy-policy">Privacy Policy</Link><Link to="/disclaimer">Disclaimer</Link></div><small>© {new Date().getFullYear()} {business.name}. Property prices, availability, dimensions and images are subject to change. Buyers should independently verify all details and MahaRERA information.</small></footer> }

function useProperties() {
  const [properties, setProperties] = useState<Property[]>(demoProperties); const [loading, setLoading] = useState(Boolean(supabase))
  useEffect(() => { if (!supabase) return; supabase.from('properties').select('*').eq('status','published').order('created_at',{ascending:false}).then(({data,error}) => { if (!error && data) setProperties(data as Property[]); setLoading(false) }) }, [])
  return { properties, loading }
}

function PropertyCard({ property }: { property: Property }) { return <article className="property-card"><div className="property-image"><img src={image(property)} alt={property.title} loading="lazy"/><span className="pill">For {property.purpose === 'sale' ? 'Sale' : 'Rent'}</span>{property.featured && <span className="featured">Featured</span>}<button aria-label="Save property"><Heart size={18}/></button></div><div className="property-body"><p>{property.locality}, {property.city}</p><h3>{property.title}</h3><strong>{money(property)}</strong><small>{property.bedrooms ? `${property.bedrooms} BHK · ` : ''}{property.bathrooms ? `${property.bathrooms} Bath · ` : ''}{property.carpet_area ? `${property.carpet_area} ${property.area_unit || 'sq ft'}` : property.category}</small><Link to={`/property/${property.slug}`}>View details <span>→</span></Link></div></article> }

function Home() { const { properties } = useProperties(); return <><section className="hero"><div className="hero-overlay"/><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="hero-copy"><p className="kicker light">Real Estate Consultancy · Nashik</p><h1>Trusted property<br/>guidance, <em>well placed.</em></h1><p>{business.tagline}. Buy, sell, rent and invest in Nashik with confidence.</p><div className="hero-ctas"><Link className="gold-button" to="/properties">Explore Properties</Link><Link className="ghost-button" to="/list-your-property">List Your Property</Link></div></motion.div><SearchBox/></section><section className="section"><p className="kicker">Featured properties</p><div className="section-title"><h2>Homes with a<br/><em>better point of view.</em></h2><Link to="/properties">See all properties →</Link></div><div className="property-grid">{properties.slice(0,3).map(p => <PropertyCard key={p.id} property={p}/>)}</div></section><section className="trust-section"><div><p className="kicker light">Why AK Vista</p><h2>Expertise in the<br/><em>details that matter.</em></h2></div><div className="trust-list">{['Verified Property Options','Local Nashik Market Expertise','Honest, Transparent Guidance','End-to-End Property Assistance','Site Visit Coordination','Home Loan & Documentation Support'].map((item,i) => <div key={item}><span>0{i+1}</span>{item}</div>)}</div></section><section className="section"><p className="kicker">Explore Nashik</p><div className="locality-grid">{localities.map(l => <Link key={l} to={`/properties?location=${encodeURIComponent(l)}`}><span>{l}</span><b>↗</b></Link>)}</div></section><section className="list-cta"><p className="kicker light">Property owners</p><h2>Ready to make your<br/><em>property visible?</em></h2><p>Share your details with AK Vista. Every submission is personally reviewed before it can be published.</p><Link className="gold-button" to="/list-your-property">Submit your property</Link></section></> }

function SearchBox() { const navigate = useNavigate(); const [location,setLocation]=useState(''); return <form className="search-box" onSubmit={e => {e.preventDefault(); navigate(`/properties${location ? `?location=${encodeURIComponent(location)}` : ''}`)}}><label>Looking to<select defaultValue="sale"><option value="sale">Buy</option><option value="rent">Rent</option></select></label><label>Property type<select><option>Any property</option><option>Apartment</option><option>Villa</option><option>Commercial</option><option>Plot</option></select></label><label>Location<input value={location} onChange={e => setLocation(e.target.value)} placeholder="Nashik locality"/></label><button className="gold-button" type="submit"><Search size={17}/> Search</button></form> }

function Properties() { const {properties,loading}=useProperties(); const loc = new URLSearchParams(useLocation().search).get('location') || ''; const [query,setQuery]=useState(loc); const [purpose,setPurpose]=useState('all'); const shown = useMemo(() => properties.filter(p => (!query || `${p.locality} ${p.title}`.toLowerCase().includes(query.toLowerCase())) && (purpose==='all'||p.purpose===purpose)),[properties,query,purpose]); return <section className="page section"><p className="kicker">Find your place</p><h1>Properties in <em>Nashik</em></h1><div className="property-toolbar"><div><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search locality or property"/></div><select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="all">Buy & Rent</option><option value="sale">For Sale</option><option value="rent">For Rent</option></select><span>{loading ? 'Loading…' : `${shown.length} properties found`}</span></div>{shown.length ? <div className="property-grid">{shown.map(p=><PropertyCard key={p.id} property={p}/>)}</div> : <div className="empty"><Building2/><h2>No properties match that search.</h2><button onClick={()=>{setQuery('');setPurpose('all')}}>Clear filters</button></div>}</section> }

function PropertyDetails() { const {slug}=useParams(); const {properties}=useProperties(); const p=properties.find(x=>x.slug===slug); if(!p) return <Navigate to="/properties" replace/>; const message=encodeURIComponent(`Hello AK Vista, I am interested in ${p.title} located at ${p.locality}. Please share more details.`); return <section className="page property-detail"><div className="detail-image"><img src={image(p)} alt={p.title}/></div><div><p className="kicker">{p.locality}, Nashik · For {p.purpose}</p><h1>{p.title}</h1><h2>{money(p)}</h2><div className="facts"><span>{p.bedrooms || '—'}<small>Bedrooms</small></span><span>{p.bathrooms || '—'}<small>Bathrooms</small></span><span>{p.carpet_area || '—'}<small>{p.area_unit || 'sq ft'}</small></span></div><p>{p.description || 'A thoughtfully selected demo property from AK Vista. Contact us for current availability, site visit coordination and complete documentation.'}</p>{p.rera_number && <p><b>MahaRERA:</b> {p.rera_number}</p>}<div className="detail-actions"><a className="gold-button" href={`${business.whatsappHref}?text=${message}`} target="_blank" rel="noreferrer">WhatsApp enquiry</a><a className="outline-button" href={business.phoneHref}>Call AK Vista</a></div></div></section> }
