import { Link, Route, Routes } from 'react-router-dom'
import { Phone } from 'lucide-react'
import { AdminDashboard, AdminGuard, AdminLogin, ListYourProperty } from './Admin'
import { business } from './config/business'
import PublicProperties from './PublicProperties'
import AdminPropertyForm from './AdminPropertyForm'
import FounderSection from './FounderSection'

function SiteHeader(){return <header className="header"><Link className="logo" to="/"><span>AK</span> VISTA<i/></Link><nav><Link to="/properties">Properties</Link><Link to="/buy">Buy</Link><Link to="/rent">Rent</Link><Link to="/commercial">Commercial</Link><Link to="/plots">Plots</Link><Link to="/contact">Contact</Link></nav><div className="header-actions"><a href={business.phoneHref}><Phone size={17}/></a><Link className="gold-button" to="/list-your-property">List Your Property</Link></div></header>}
function Landing(){return <><section className="hero"><div className="hero-overlay"/><div className="hero-copy"><p className="kicker light">Real Estate Consultancy · Nashik</p><h1>Trusted property<br/>guidance, <em>well placed.</em></h1><p>{business.tagline}. Buy, sell, rent and invest in Nashik with confidence.</p><div className="hero-ctas"><Link className="gold-button" to="/properties">Explore Properties</Link><Link className="ghost-button" to="/list-your-property">List Your Property</Link></div></div></section><FounderSection/><section className="section"><p className="kicker">Owner-first moderation</p><h2>Every listing is<br/><em>reviewed before public release.</em></h2><p className="form-intro">Property owners can securely submit property details and photos. Their listings stay pending until an authorised AK Vista administrator approves and publishes them from the dashboard.</p><Link className="gold-button" to="/list-your-property">Submit your property</Link></section></>}
function Placeholder({title}:{title:string}){return <section className="page section"><p className="kicker">AK Vista · Nashik</p><h1>{title}</h1><p className="form-intro">Browse our verified property opportunities, or talk to AK Vista for a tailored shortlist.</p><Link className="gold-button" to="/properties">Explore properties</Link></section>}
function SiteFooter(){return <footer className="footer"><div><b>AK VISTA</b><p>Independent Real Estate Consultant<br/>{business.city}</p></div><div><a href={business.phoneHref}>{business.phone}</a><a href={`mailto:${business.email}`}>{business.email}</a></div><small>Property prices, availability, dimensions and images are subject to change. Buyers should independently verify all details, legal documents and MahaRERA information.</small></footer>}
export default function Router(){return <><SiteHeader/><Routes><Route path="/" element={<Landing/>}/><Route path="/properties" element={<PublicProperties/>}/><Route path="/buy" element={<Placeholder title="Buy property"/>}/><Route path="/rent" element={<Placeholder title="Rental properties"/>}/><Route path="/commercial" element={<Placeholder title="Commercial properties"/>}/><Route path="/plots" element={<Placeholder title="Plots & land"/>}/><Route path="/contact" element={<Placeholder title="Contact AK Vista"/>}/><Route path="/list-your-property" element={<ListYourProperty/>}/><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin" element={<AdminGuard><AdminDashboard/></AdminGuard>}/><Route path="/admin/properties/new" element={<AdminGuard><AdminPropertyForm/></AdminGuard>}/><Route path="/admin/properties/:id/edit" element={<AdminGuard><AdminPropertyForm/></AdminGuard>}/><Route path="*" element={<Landing/>}/></Routes><SiteFooter/></>}
